theme = "current_theme"

[editor]
bufferline = "multiple"
jump-label-alphabet = "aoeuidhtnspgcrlmbkjvwfyqxz"
line-number = "relative"
mouse = false
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-r = ":reload-all"
C-g = "goto_word"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
W = ":wa!"
c = ":bc!"
C = ":bca!"

[keys.normal.";"]
b = ":sh hx_ide_wez blame"
e = ":sh hx_ide_wez explorer"
f = ":sh hx_ide_wez cfp"
i = ":toggle-option file-picker.git-ignore"
l = ":sh hx_ide_wez lint"
m = ":sh hx_ide_wez md-preview"
p = ":sh hx_ide_wez pane"
s = ":sh hx_ide_wez search"
t = ":sh hx_ide_wez test"
